CREATE TABLE USERS(ID INT PRIMARY KEY, NAME VARCHAR(255) NOT NULL UNIQUE, PASSWORD VARCHAR(255), ROLE INT);

INSERT INTO USERS VALUES(1,'Alexandr','Alex', 3);
INSERT INTO USERS VALUES(2,'Alexa','Alexandr', 2);
INSERT INTO USERS VALUES(3,'Trofim@Trofim','125', 1);
INSERT INTO USERS VALUES(4,'IvanKravec','Alexandr', 4);
INSERT INTO USERS VALUES(5,'&Zinnedin','   ', 4);
INSERT INTO USERS VALUES(6,'Agar','', 1);
INSERT INTO USERS VALUES(7,'Foot','HHhHH', 2);
INSERT INTO USERS VALUES(8,'Michiel Owen','Michiel Owen', 2);

select * from USERS;

commit