CREATE TABLE USERS(ID INT PRIMARY KEY, LOGIN VARCHAR(50) NOT NULL UNIQUE, NAME VARCHAR(50), LAST_NAME VARCHAR(50),
EMAIL VARCHAR(100), PASSWORD VARCHAR(200), ROLE_ID INTEGER, ACTIVE BOOLEAN);

INSERT INTO USERS VALUES(1,'ALEX','Alexandr', 'Sumaneyev', 'as@mail.ru', '1',  2, TRUE);

/*todo изменить. добавлены новые параметры*/
INSERT INTO USERS VALUES(1,'Alexandr','Alex', 3);
INSERT INTO USERS VALUES(2,'Alexa','Alexandr', 2);
INSERT INTO USERS VALUES(3,'Trofim@Trofim','125', 1);
INSERT INTO USERS VALUES(4,'IvanKravec','Alexandr', 4);
INSERT INTO USERS VALUES(5,'&Zinnedin','   ', 4);
INSERT INTO USERS VALUES(6,'Agar','', 1);
INSERT INTO USERS VALUES(7,'Foot','HHhHH', 2);
INSERT INTO USERS VALUES(8,'Michiel Owen','Michiel Owen', 2);

select * from USERS;

commit